# Generated by Django 2.2.1 on 2019-07-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat', models.DecimalField(choices=[(0.23, '23%'), (0.08, '8%'), (0.05, '5%'), (0, '0%')], decimal_places=2, default=0.23, max_digits=3)),
                ('stock', models.IntegerField()),
                ('categories', models.ManyToManyField(to='shopper.Category')),
            ],
        ),
    ]
