# Generated by Django 2.2.1 on 2019-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0002_auto_20190729_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(choices=[(0.23, '23%'), (0.08, '8%'), (0.05, '5%'), (0, '0%')], decimal_places=2, max_digits=6),
        ),
    ]
