# Generated by Django 2.2.1 on 2019-07-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_auto_20190729_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.23, max_digits=3),
        ),
    ]
